### ISSUE TITLE
[BUG] CosmosDB Spring Boot Starter -  pagination falls into endless loop

### ISSUE THREAD

**Issue by mkarczewski85** [Azure/azure-sdk-for-java#13442]
**Description**
I have to implement CSV export app for stored IoT data. Usually exported data includes huge amount of documents (1 week = about 300 000 docs), so my logic have to use pagination. There are only two conditions: 1) partition key (**I don't perform cross-partition query**), 2) timestamp range (BETWEEN clause).
My Java Spring app uses 'Azure Cosmos DB Spring Boot Starter' version 2.3.2. I'm comply with recommended way described [here](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb).

**Code snippet**
```java
Sort sort = Sort.by(Sort.Direction.DESC, "dataTimestamp");
Pageable pageable = CosmosPageRequest.of(0, 1000, null, sort);
Page<DataReading> dataPage = dataReadingRepository
                .findByPartitionKeyAndDataTimestampBetween(partitionKey, start, end, pageable);
List<DataReading> content = dataPage.getContent();
// (...) write data to CSV - omitted for brevity
while (dataPage.hasNext()) {
    pageable = dataPage.nextPageable();
    dataPage = dataReadingRepository
                .findByPartitionKeyAndDataTimestampBetween(partitionKey, start, end, pageable);
    // (...) write data to CSV - omitted for brevity
}
```
**Single document structure**

```json
{
"dataTimestamp": 1592940236592,
"deviceId": "xxx",
"sensorFamily": "yyy",
"measurementType": "temperature",
"dataKey": "zzz",
"reading": 23.1,
"partitionKey": "xxx-zzz",
"id": "c610a0e1-79c0-1bd0-109d-132b3fd0ab97",
"_rid": "xVQwAO79jhVSzAwAAAAACw==",
"_self": "dbs/xVQwAA==/colls/xVQwAO79jhU=/docs/xVQwAO79jhVSzAwAAAAACw==/",
"_etag": "\"0800ba43-0000-0400-0000-5ef256ce0000\"",
"_attachments": "attachments/",
"_ts": 1592940238
}
```

**Expected behavior**

pagination falls into an endless loop. What I mean by that? This is how first page looks like this:
![image](https://user-images.githubusercontent.com/27696392/88256844-97262980-ccbc-11ea-8674-2a2541401426.png)

And this is fine. Total elements aligns with the query count performed in CosmosDB web client:
![image](https://user-images.githubusercontent.com/27696392/88256875-b02eda80-ccbc-11ea-96b0-2149e51f3459.png)

And this is how second page looks like:
![image](https://user-images.githubusercontent.com/27696392/88256904-c2107d80-ccbc-11ea-96e4-4c362281d48d.png)

**The while loop never ends.** There's always nextPage() (totalElements increases after query reach previous value).
Fetched data contains documents duplicated with data retrieved in previous pages, and documents are mixed inconsistently with the sort.

**What I've tried**
- changing Pageable object to CosmosPageRequest (no effect)
- changing Page object to CosmosPageImpl (no effect)

**Setup (please complete the following information):**
 - OS: Windows (dev), Linux (prod)
 - IDE : IntelliJ
 - Azure Cosmos DB Spring Boot Starter' version 2.3.2

**Additional context**
- max RU - 50 000 
- Indexing policy - default (didn't changed or add anything)
- I don't modify requestContinuation field (with continuation token) at any stage
- I don't experience RequestTooLarge exceptions

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by yiliuTo** [comment]
Hi @kushagraThapar , would you help to take a look of this？It seems to be an issue with cosmosdb sdk instead of starter. Thanks~

**Comment by kushagraThapar** [comment]
@mkarczewski85 - I think this is a known `order by` issue and seems like this was fixed in v4.1.0. You can check it in release notes here : https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java-v4#key-bug-fixes-1

Since spring-data-cosmosdb v2.3.x is based on v3 SDK, we won't be able to backport this fix to V3 SDK soon. 

Could you wait a couple of weeks for this fix and we will be releasing spring-data-cosmosdb v3.0.0-beta.1 based on azure-cosmos V4 SDK. That should work fine in this case. 

Let me know!

**Comment by mkarczewski85** [comment]
@kushagraThapar - well I tried to run same query without sorting, which should prevent SDK from adding ```order by``` to the query string.  Same effect:

First page:
![cosm1](https://user-images.githubusercontent.com/27696392/88661775-5de52380-d0d9-11ea-985a-2fe350b8f61f.png)
Second page:
![cosm2](https://user-images.githubusercontent.com/27696392/88661778-5e7dba00-d0d9-11ea-9265-b73358773e12.png)

And the rest goes as I previously described.

**Comment by kushagraThapar** [comment]
@mkarczewski85 - I tried reproducing the above issue in v2.3.x spring-data-cosmosdb and I am not seeing the above issue. 

Here is my PR against v2.3.x version of spring-data-cosmosdb : https://github.com/microsoft/spring-data-cosmosdb/pull/549/files

Please take a look at the new test cases I have added in PageableMemoRepositoryIT which are using `findByPartitionKeyAndDateBetween` : https://github.com/microsoft/spring-data-cosmosdb/pull/549/files#diff-292c58110a1d930bfd13146540b6f5c0R114

You can try running the test case by cloning the project and testing it against either emulator or your service endpoint. It passed when I tested it. 

Regarding your above screenshots, is there any chance that you are also updating the container with new items at the same time as you are running this query ?

Because I clearly remember fixing a bug related to pagination in this release : https://github.com/microsoft/spring-data-cosmosdb/releases/tag/v2.2.1.M1

**Comment by mkarczewski85** [comment]
@kushagraThapar I switched to spring-data-cosmosdb (v.2.2.1.M1 and later) but I still experience described issue (both sorted and unsorted). Regarding your question: does updating the container with new items at the same time as running query somehow affects query results? My query has search criteria based on write timestamps (between clause), so any new items (which aren't  satisfy query criteria) should be omitted by db engine. 

I'm beginning to suspect that the CosmosDB itself could be the source of the problem. Maybe there's too much data to be processed in one request (that's way you are not able to reproduce my issue). To be 100% sure I will try to use pure Java SDK without Spring related dependencies.

**Comment by kushagraThapar** [comment]
@mkarczewski85 - did you try reproducing the issue with pure Java SDK ?
What were the results with Java SDK ?

**Comment by mkarczewski85** [comment]
@kushagraThapar I tried to use pure SDK with SqlQuerySpec and FeedOptions and after many tests I can say that described issue do not occur. The only difference is that pagination doesn't work properly. When I give page size of let's say 1000 records I receive only 850.  It's not a problem for me because I want to fetch all the data in order to write it to csv file, so it desn't matter if the page size is equal to 1000 or 850 (but it's always less than I requested). I pass continuation token directly to cotainer:

```java 
Iterable<FeedResponse<DataReading>> feedResponseIterator = container
					.queryItems(sqlQuerySpec, options, DataReading.class)
					.iterableByPage(continuationToken, pageSize);
```
This means that the root cause of the issue is in the CosmosDB Spring Boot client code. I don't have enough time to find it by myself (maybe later I will be able to devote some time to do it). Nevertheless, we decided to migrate from CosmosDB to ElasticSearch which better meets our requirements.
propably, the only way to reproduce this issue is to fill database with GBs of partitioned data and then try to query it with pagination.

**Comment by kushagraThapar** [comment]
@mkarczewski85 - that sounds good. Cosmos DB doesn't always return the exact page size (which is provided by the end user). It provides results which are less than equal to preferred page size. So from that perspective, what you are receiving looks correct. 

Regarding spring data pagination, since I added the pagination test case which inputs high volume of data and run the tests fine, I am closing this case. 

We can re-open this issue in future if the problem persists with the latest SDK version of spring that is currently in progress and will be released GA soon (by the end of September)
