### ISSUE TITLE
[QUERY] Issues while upgrading to com.azure:azure-messaging-eventhubs:5.2.0

### ISSUE THREAD

**Issue by ShubhaPradeep** [Azure/azure-sdk-for-java#15621]
We are trying to upgrade to azure-messaging-eventhubs:5.2.0 and are having issue. We would like to know what are the other dependencies to be upgraded along with 5.2?
One of the issues we encountered when we upgraded was, build could not resolve one of the methods in reactor core and we got the below error.
**'reactor.core.scheduler.Scheduler reactor.core.scheduler.Schedulers.boundedElastic()'**

 So we upgraded reactor core. Now we see the below error when we try to test,
**Caused by: java.lang.IllegalStateException: Failed to register bean with name 'bf77d7d7-bb4d-4af5-b62f-f827d0b97422.bf77d7d7-bb4d-4af5-b62f-f827d0b97422.errors.recoverer', since bean with the same name already exists. Possible reason: You may have multiple bindings with the same 'destination' and 'group' name (consumer side) and multiple bindings with the same 'destination' name (producer side). Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side).** 

We are trying to upgrade to 5.2 to see if it stops a production issue which we have frequently seen which is "org.springframework.messaging.MessageDeliveryException: errorCondition[amqp:connection:framing-error]. description[org.apache.qpid.proton.engine.TransportException: connection aborted], errorContext[NAMESPACE". 
Will upgrading to 5.2 stop the above error?

We want to know the other dependencies to be upgraded. 

**Setup (please complete the following information if applicable):**
 - IDE :  IntelliJ
 
Below is the gradle setup

**implementation 'com.microsoft.azure:azure:1.33.0'
    implementation 'com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.2.0'
    implementation 'com.azure:azure-messaging-eventhubs:5.2.0'
    compile group: 'io.projectreactor', name: 'reactor-core', version: '3.3.10.RELEASE'**

**Comment by joshfree** [comment]
Sorry that you're running into an issue while upgrading versions.  @YijunXieMS could you please take a look and provide guidance?

**Comment by ShubhaPradeep** [comment]
Thanks @joshfree, looking forward to resolving it.

**Comment by srnagar** [comment]
@ShubhaPradeep You only need to include `com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.2.0` in your dependency. `azure-messaging-eventhubs` and `reactor-core` will be transitively included. Also, do you have any other dependencies from `com.azure` group?
Can you try removing the following 2 lines from your gradle setup?
```
implementation 'com.azure:azure-messaging-eventhubs:5.2.0'
compile group: 'io.projectreactor', name: 'reactor-core', version: '3.3.10.RELEASE'
```

**Comment by ShubhaPradeep** [comment]
Thanks @srnagar. We tried per your suggestion but Schedulers.boundedElastic() in PartitionPumpManager.java cannot find the method.
![image](https://user-images.githubusercontent.com/62150723/94194912-572c2000-fe80-11ea-884d-adbd7f7c2f9c.png)

**Comment by ShubhaPradeep** [comment]
When we tried to test with azure-messaging-eventhubs-checkpointstore-blob:1.2.0, we did not get any error related to Schedulers.boundedElastic(). But we get the below error. Looks like we are able to publish the message to eventhub but cannot read from it. We did not have this issue before upgrade.

**Caused by: java.lang.IllegalStateException: Failed to register bean with name 'bf77d7d7-bb4d-4af5-b62f-f827d0b97422.bf77d7d7-bb4d-4af5-b62f-f827d0b97422.errors.recoverer', since bean with the same name already exists. Possible reason: You may have multiple bindings with the same 'destination' and 'group' name (consumer side) and multiple bindings with the same 'destination' name (producer side). Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side).**

**Comment by srnagar** [comment]
@ShubhaPradeep - so after updating gradle to only have `azure-messaging-eventhubs-checkpointstore-blob:1.2.0`, the issue with `Schedulers.boundedElastic()` is resolved, right?

Regarding the spring bean issue, it seems like the destination and group name are the same and that's why it's unable to initialize the bean. Can you try this? "Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side)."

**Comment by ShubhaPradeep** [comment]
> @ShubhaPradeep - so after updating gradle to only have `azure-messaging-eventhubs-checkpointstore-blob:1.2.0`, the issue with `Schedulers.boundedElastic()` is resolved, right?
> 
> Regarding the spring bean issue, it seems like the destination and group name are the same and that's why it's unable to initialize the bean. Can you try this? "Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side)."

Thank you for your help.

**Comment by srnagar** [comment]
@ShubhaPradeep Can you please confirm if the issue is fixed? If so, could you also please post the resolution for the benefit of others who might have run into similar issues?

**Comment by ShubhaPradeep** [comment]
@srnagar our issue is not resolved. After upgrading to **'com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.2.0'**, we are seeing the below issue. But method not found exception for this method Schedulers.boundedElastic() is resolved.

**Caused by: java.lang.IllegalStateException: Failed to register bean with name 'bf77d7d7-bb4d-4af5-b62f-f827d0b97422.bf77d7d7-bb4d-4af5-b62f-f827d0b97422.errors.recoverer', since bean with the same name already exists. Possible reason: You may have multiple bindings with the same 'destination' and 'group' name (consumer side) and multiple bindings with the same 'destination' name (producer side). Solution: ensure each binding uses different group name (consumer side) or 'destination' name (producer side).**

We are doing our research to see how to fix it.

**Comment by srnagar** [comment]
Thanks for the clarification. So, the originally reported issue about `Schedulers.boundedElastic()` not found is resolved. So, we can keep this issue closed.

However, if you think that the spring binder for Event Hubs is causing this issue of multiple bindings having the same name, please file another issue.

Thank you!
