### ISSUE TITLE
[BUG] Could not initialize class reactor.netty.http.client.HttpClientSecure

### ISSUE THREAD

**Issue by thilagak** [Azure/azure-sdk-for-java#19041]
Description:
  I am trying java sdk samples for Azure resource manager and it seems there is a class reference issue for the reactor library. 

1) When I use below maven dependencies
  ```
  <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-http-netty</artifactId>
      <version>1.6.3</version>
    </dependency>  <!--
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
      <version>3.6</version>
    </dependency>  -->
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-trafficmanager</artifactId>
     <version>2.1.0</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.projectreactor/reactor-core -->
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.4.1</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>1.0.2</version>
    </dependency>
```
I get below runtime error. I do see reactor.netty.http.client.HttpClientSecure not exist with reactor as per https://javadoc.io/doc/io.projectreactor.netty/reactor-netty/latest/index.html java doc.

```
java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: Could not initialize class reactor.netty.http.client.HttpClientSecure
        at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
        at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2023)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:192)
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:259)
        at reactor.core.publisher.FluxMap$MapSubscriber.onError(FluxMap.java:132)
        at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:76)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
        Suppressed: java.lang.Exception: #block terminated with an error
                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
                at reactor.core.publisher.Flux.blockLast(Flux.java:2510)
                at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50)
                at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37)
                at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106)
                at java.lang.Iterable.forEach(Unknown Source)
                at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultSubscription(ResourceManagerUtils.java:120)
                at com.azure.resourcemanager.AzureResourceManager$AuthenticatedImpl.withDefaultSubscription(AzureResourceManager.java:339)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
                at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
                at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
                at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
                at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
                at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
                at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
                at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
                at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:217)
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57)
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:76)
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:269)
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4046)
        at reactor.core.publisher.Mono.block(Mono.java:1702)
        at com.azure.identity.implementation.HttpPipelineAdapter.send(HttpPipelineAdapter.java:59)
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequestWithRetries(HttpHelper.java:86)
        at com.microsoft.aad.msal4j.HttpHelper.executeHttpRequest(HttpHelper.java:64)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.sendInstanceDiscoveryRequest(AadInstanceDiscoveryProvider.java:119)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.doInstanceDiscoveryAndCache(AadInstanceDiscoveryProvider.java:135)
        at com.microsoft.aad.msal4j.AadInstanceDiscoveryProvider.getMetadataEntry(AadInstanceDiscoveryProvider.java:42)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.getAuthorityWithPrefNetworkHost(AuthenticationResultSupplier.java:32)
        at com.microsoft.aad.msal4j.AcquireTokenByAuthorizationGrantSupplier.execute(AcquireTokenByAuthorizationGrantSupplier.java:59)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:59)
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
        ... 6 more

```

2) When I remove reactor library dependencies
```
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-core-http-netty</artifactId>
      <version>1.6.3</version>
    </dependency>  <!--
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
      <version>3.6</version>
    </dependency>  -->
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-trafficmanager</artifactId>
     <version>2.1.0</version>
    </dependency>
```
I get below runtime error.
```
2021-02-07 18:22:58.659 ERROR 8888 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: reactor.util.context.Context.of(Ljava/util/Map;)Lreactor/util/context/Context;] with root cause

java.lang.NoSuchMethodError: reactor.util.context.Context.of(Ljava/util/Map;)Lreactor/util/context/Context;
	at com.azure.core.util.FluxUtil.toReactorContext(FluxUtil.java:311) ~[azure-core-1.10.0.jar!/:na]
	at com.azure.resourcemanager.resources.implementation.SubscriptionsClientImpl.lambda$listSinglePageAsync$11(SubscriptionsClientImpl.java:352) ~[azure-resourcemanager-resources-2.1.0.jar!/:2.1.0]
	at reactor.core.publisher.MonoSubscriberContext.subscribe(MonoSubscriberContext.java:40) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxSourceMonoFuseable.subscribe(FluxSourceMonoFuseable.java:38) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxSwitchIfEmpty.subscribe(FluxSwitchIfEmpty.java:45) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Flux.subscribe(Flux.java:6877) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxExpand$ExpandBreathSubscriber.drainQueue(FluxExpand.java:171) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxExpand.subscribe(FluxExpand.java:70) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:55) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at reactor.core.publisher.Flux.blockLast(Flux.java:2051) ~[reactor-core-3.1.8.RELEASE.jar!/:3.1.8.RELEASE]
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94) ~[azure-core-1.10.0.jar!/:na]
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50) ~[azure-core-1.10.0.jar!/:na]
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37) ~[azure-core-1.10.0.jar!/:na]
	at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106) ~[azure-core-1.10.0.jar!/:na]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_271]
	at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultSubscription(ResourceManagerUtils.java:120) ~[azure-resourcemanager-resources-2.1.0.jar!/:2.1.0]
	at com.azure.resourcemanager.AzureResourceManager$AuthenticatedImpl.withDefaultSubscription(AzureResourceManager.java:339) ~[azure-resourcemanager-2.1.0.jar!/:2.1.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_271]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_271]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_271]

```

I followed all the steps as per https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/resourcemanager.
Please let me know is it a bug or I miss anything.

Regards
Thilaga

**Comment by SrinivasGanesan** [comment]
Error is unable to locate HttpClientSecure class in RE.

HttpClientSecure Class belongs to reactor-netty(1.0.3) package.

I am using all these dependencies in my project. So Add these dependencies and try,

<dependency>
	<groupId>io.projectreactor.netty</groupId>
	<artifactId>reactor-netty</artifactId>
	<version>1.0.3</version>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-core</artifactId>
	<version>3.4.2</version>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-test</artifactId>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-handler</artifactId>
</dependency>
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-tcnative-boringssl-static</artifactId>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-test</artifactId>
	<scope>test</scope>
</dependency>

**Comment by thilagak** [comment]
Further update:

It seemed like "the root cause is that you most likely have compiled a class against a different version of the class that is missing a method, than the one you are using when running it." as per [stackoverflow](https://stackoverflow.com/questions/35186/how-do-i-fix-a-nosuchmethoderror). So tried all versions of reactor-core library. Below is the result:

UNTIL version 3.2.10.RELEASE, it is java.lang.NoSuchMethodError: reactor.util.context.Context.of(Ljava/util/Map;)Lreactor/util/context/Context;

FROM 3.2.11.RELEASE version, it is java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure


So what is the right reactor-core library version to use with azure-identity of 1.2.0 version.

**Comment by thilagak** [comment]
> Error is unable to locate HttpClientSecure class in RE.
> 
> HttpClientSecure Class belongs to reactor-netty(1.0.3) package.
> 
> I am using all these dependencies in my project. So Add these dependencies and try,
> 
> ```
> <dependency>
> 	<groupId>io.projectreactor.netty</groupId>
> 	<artifactId>reactor-netty</artifactId>
> 	<version>1.0.3</version>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-core</artifactId>
> 	<version>3.4.2</version>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-test</artifactId>
> 	<scope>test</scope>
> </dependency>
> <dependency>
> 	<groupId>io.netty</groupId>
> 	<artifactId>netty-handler</artifactId>
> </dependency>
> <dependency>
> 	<groupId>io.netty</groupId>
> 	<artifactId>netty-tcnative-boringssl-static</artifactId>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-test</artifactId>
> 	<scope>test</scope>
> </dependency>
> ```

**Comment by SrinivasGanesan** [comment]
Worked???

**Comment by thilagak** [comment]
> Error is unable to locate HttpClientSecure class in RE.
> 
> HttpClientSecure Class belongs to reactor-netty(1.0.3) package.
> 
> I am using all these dependencies in my project. So Add these dependencies and try,
> 
> ```
> <dependency>
> 	<groupId>io.projectreactor.netty</groupId>
> 	<artifactId>reactor-netty</artifactId>
> 	<version>1.0.3</version>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-core</artifactId>
> 	<version>3.4.2</version>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-test</artifactId>
> 	<scope>test</scope>
> </dependency>
> <dependency>
> 	<groupId>io.netty</groupId>
> 	<artifactId>netty-handler</artifactId>
> </dependency>
> <dependency>
> 	<groupId>io.netty</groupId>
> 	<artifactId>netty-tcnative-boringssl-static</artifactId>
> </dependency>
> <dependency>
> 	<groupId>io.projectreactor</groupId>
> 	<artifactId>reactor-test</artifactId>
> 	<scope>test</scope>
> </dependency>
> ```

Thank you @SrinivasGanesan . I used same dependencies still getting "HttpClientSecure" and verified versions of all jars inside my application package and all looks good. Any thoughts?

Regards
Thilaga

**Comment by thilagak** [comment]
Update:

Still trying to find a right versions for below dependencies:
```

    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>?</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>?</version>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-trafficmanager</artifactId>
     <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>?</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>?</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty-http</artifactId>
      <version>?</version>
    </dependency>

```
It seems like "HttpClientSecure" class exist in reactor-netty-http but not in reactor-netty.

Regards
Thilaga

**Comment by alzimmermsft** [comment]
Thank you for filing this issue @thilagak!

The Azure SDK libraries are currently using the `0.9.x` versions of `reactor-netty` with the latest releases using `0.9.15.RELEASE`. In an upcoming, to be determined, release will we be upgrading to the `1.0.x` releases. Between `0.9.x` and `1.0.x` there are compatibility breaking changes in `reactor-netty` which is why you are seeing this issue as the package/module has been moved.

cc: @SrinivasGanesan

**Comment by thilagak** [comment]
Hi @alzimmermsft ,

Thank you for the info. Below are my tried settings with no luck. Can you please help me to get right version?
```

    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
    </dependency>

```
```

    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.projectreactor.netty</groupId>
          <artifactId>reactor-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.1.8.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.12.RELEASE</version>
    </dependency>

```
```

    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.projectreactor.netty</groupId>
          <artifactId>reactor-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.1.8.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.12.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty-http</artifactId>
      <version>1.0.0</version>
    </dependency>

```

Like said in the previous post, tried different combinations of versions between reactor-core and reactor-netty. Later found that "HttpClientSecure" class is in reactor-netty-http. Tried that too but no luck.

Regards
Thilaga

**Comment by alzimmermsft** [comment]
Oh yes, I missed a bit in my explanation, the Azure SDKs are currently using the `3.3.x` release track for `reactor-core`. In a similar vein, `reactor-core` has API differences between `3.1.x` in the configuration you linked and `3.3.x` being used as the SDK dependency. And the same as above we are looking to upgrade to `3.4.x` in an upcoming release.

With that, using `reactor-netty` `0.9.x` releases and `reactor-core` `3.3.x` releases should resolve the mentioned class and method not found exceptions. You can also remove the `reactor-netty-http` dependency as that doesn't exist in their `0.9.x` release track and was introduced in their `1.0.x` track.

**Comment by thilagak** [comment]
Tried below but same result [`Caused by: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure`].

    ```
<dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.projectreactor.netty</groupId>
          <artifactId>reactor-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-trafficmanager</artifactId>
     <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.3.10.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.12.RELEASE</version>
    </dependency>
```

Regards
Thilaga

**Comment by SrinivasGanesan** [comment]
Have u resolved this issue? I am also got stuck here.

**Comment by thilagak** [comment]
Sorry @SrinivasGanesan. Since this is not moving anywhere I am not sure if the SDK is broken. I am continueing my development with Azure api using Apache http client library. I am not using this SDK for now.

**Comment by alzimmermsft** [comment]
Hi @thilagak, using the POM configuration sent I wasn't able to reproduce the class/method not found exceptions. Are there other dependencies being used in the project that aren't listed?

**Comment by thilagak** [comment]
Hi @alzimmermsft , here is my pom.xml

```

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.3.RELEASE</version>
  </parent>

  <properties>
    <java.version>1.8</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <fork>true</fork>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
            <configuration>
              <additionalProperties>
                <encoding.source>UTF-8</encoding.source>
                <encoding.reporting>UTF-8</encoding.reporting>
                <java.source>${java.version}</java.source>
                <java.target>${java.version}</java.target>
              </additionalProperties>
            </configuration>
          </execution>
        </executions>
      </plugin>  <!--
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>citrix.trafficmanagement.ctm.Application</mainClass>
            </manifest>
          </archive>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.3</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <source>${java.version}</source>
              <target>${java.version}</target>
              <archive>
                <manifest>
                  <mainClass>
                    citrix.trafficmanagement.ctm.Application
                  </mainClass>
                </manifest>
              </archive>
              <finalName>${project.artifactId}</finalName>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>  -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
     <!-- Rest Controller -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.googlecode.json-simple</groupId>
      <artifactId>json-simple</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager</artifactId>
      <version>2.1.0</version>
    </dependency>
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-identity</artifactId>
      <version>1.2.0</version>
      <exclusions>
        <exclusion>
          <groupId>io.projectreactor</groupId>
          <artifactId>reactor-core</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.projectreactor.netty</groupId>
          <artifactId>reactor-netty</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.azure.resourcemanager</groupId>
      <artifactId>azure-resourcemanager-trafficmanager</artifactId>
     <version>2.1.0</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/io.projectreactor/reactor-core -->
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.3.10.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor.netty</groupId>
      <artifactId>reactor-netty</artifactId>
      <version>0.9.12.RELEASE</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

```

Regards
Thilaga

**Comment by alzimmermsft** [comment]
Thank you so much @thilagak, that helped me locate the root issue. 

The Azure SDKs you are using are compatible with later versions of Spring Framework 2.2.x and 2.3.x. What I found is with that Spring parent version the underlying version of `Netty` was being resolved to a much older version, `Reactor Netty` was attempting to call methods that didn't exist.

Upgrading to Spring Frame 2.3.x should resolve this issue. If that is not a possibility including [`netty-bom`](https://mvnrepository.com/artifact/io.netty/netty-bom) with a later version, such as `4.1.52.Final` (or later), should also resolve the issue.

**Comment by thilagak** [comment]
Thank you much @alzimmermsft . Sure I will have no issue in upgrading to new springboot version. Actually I had this doubt and checked my mvn dependency-tree but was not able to locate the netty library in springboot. Given below is my dependency tree. Did I overlook something?
```

[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< citrix.trafficmanagement:CTM >--------------------
[INFO] Building CTM 0.0.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.2:tree (default-cli) @ CTM ---
[INFO] citrix.trafficmanagement:CTM:jar:0.0.2-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:2.0.3.RELEASE:compile

[INFO] |  +- org.springframework.boot:spring-boot:jar:2.0.3.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.0.3.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.0.3.RELEASE:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.10.0:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.10.0:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  +- org.springframework:spring-core:jar:5.0.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.19:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.0.3.RELEASE:provided
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.0.3.RELEASE:provided
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.6:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.6:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.6:provided
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.6:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.6:provided
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.0.3.RELEASE:provided
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.31:provided
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.31:provided
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.31:provided
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:6.0.10.Final:provided
[INFO] |  |  +- javax.validation:validation-api:jar:2.0.1.Final:provided
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:provided
[INFO] |  |  \- com.fasterxml:classmate:jar:1.3.4:provided
[INFO] |  +- org.springframework:spring-web:jar:5.0.7.RELEASE:provided
[INFO] |  |  \- org.springframework:spring-beans:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.0.7.RELEASE:provided
[INFO] |     +- org.springframework:spring-aop:jar:5.0.7.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.0.7.RELEASE:compile
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] +- com.azure.resourcemanager:azure-resourcemanager:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-resources:jar:2.1.0:compile
[INFO] |  |  \- com.azure:azure-core-management:jar:1.0.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-storage:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-compute:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-network:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-keyvault:jar:2.1.0:compile
[INFO] |  |  +- com.azure:azure-security-keyvault-keys:jar:4.2.3:compile
[INFO] |  |  \- com.azure:azure-security-keyvault-secrets:jar:4.2.3:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-msi:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-sql:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-authorization:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-appservice:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-cosmos:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-containerservice:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-monitor:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-containerregistry:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-dns:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-appplatform:jar:2.1.0:compile
[INFO] |  |  \- com.azure:azure-storage-file-share:jar:12.7.0:compile
[INFO] |  |     \- com.azure:azure-storage-common:jar:12.9.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-containerinstance:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-privatedns:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-redis:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-eventhubs:jar:2.1.0:compile
[INFO] |  +- com.azure.resourcemanager:azure-resourcemanager-servicebus:jar:2.1.0:compile
[INFO] |  \- com.azure.resourcemanager:azure-resourcemanager-cdn:jar:2.1.0:compile
[INFO] +- com.azure:azure-identity:jar:1.2.0:compile
[INFO] |  +- com.azure:azure-core:jar:1.10.0:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.9.6:compile
[INFO] |  |  |  +- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.6:compile
[INFO] |  |  |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  |  |  \- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.1.8.RELEASE:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
[INFO] |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.34.Final:compile
[INFO] |  +- com.azure:azure-core-http-netty:jar:1.6.3:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.25.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport:jar:4.1.25.Final:compile
[INFO] |  |  |  |  \- io.netty:netty-resolver:jar:4.1.25.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-handler-proxy:jar:4.1.25.Final:compile
[INFO] |  |  |  \- io.netty:netty-codec-socks:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.25.Final:compile
[INFO] |  |  |  \- io.netty:netty-common:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http2:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-unix-common:jar:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.25.Final:compile
[INFO] |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.25.Final:compile
[INFO] |  |  \- io.projectreactor.netty:reactor-netty:jar:0.9.12.RELEASE:compile

[INFO] |  +- net.minidev:json-smart:jar:2.3:compile
[INFO] |  |  \- net.minidev:accessors-smart:jar:1.2:compile
[INFO] |  |     \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO] |  +- com.microsoft.azure:msal4j:jar:1.8.0:compile
[INFO] |  +- com.microsoft.azure:msal4j-persistence-extension:jar:1.0.0:compile
[INFO] |  |  \- net.java.dev.jna:jna:jar:4.5.1:compile
[INFO] |  +- com.nimbusds:oauth2-oidc-sdk:jar:7.1.1:compile
[INFO] |  |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  |  +- com.nimbusds:content-type:jar:2.0:compile
[INFO] |  |  +- com.nimbusds:lang-tag:jar:1.4.4:compile
[INFO] |  |  +- com.nimbusds:nimbus-jose-jwt:jar:8.8:compile
[INFO] |  |  \- com.sun.mail:javax.mail:jar:1.6.1:compile
[INFO] |  |     \- javax.activation:activation:jar:1.1:compile
[INFO] |  +- net.java.dev.jna:jna-platform:jar:4.5.1:compile
[INFO] |  \- org.linguafranca.pwdb:KeePassJava2:jar:2.1.4:compile
[INFO] |     +- org.linguafranca.pwdb:KeePassJava2-kdb:jar:2.1.4:compile
[INFO] |     |  +- org.linguafranca.pwdb:database:jar:2.1.4:compile
[INFO] |     |  |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |     |  |  \- com.madgag.spongycastle:core:jar:1.54.0.0:compile
[INFO] |     |  \- org.jetbrains:annotations:jar:15.0:compile
[INFO] |     +- org.linguafranca.pwdb:KeePassJava2-dom:jar:2.1.4:compile
[INFO] |     |  \- org.linguafranca.pwdb:KeePassJava2-kdbx:jar:2.1.4:compile
[INFO] |     |     \- commons-codec:commons-codec:jar:1.11:compile
[INFO] |     +- org.linguafranca.pwdb:KeePassJava2-jaxb:jar:2.1.4:compile
[INFO] |     \- org.linguafranca.pwdb:KeePassJava2-simple:jar:2.1.4:compile
[INFO] |        +- org.simpleframework:simple-xml:jar:2.7.1:compile
[INFO] |        |  +- stax:stax-api:jar:1.0.1:compile
[INFO] |        |  +- stax:stax:jar:1.2.0:compile
[INFO] |        |  \- xpp3:xpp3:jar:1.1.3.3:compile
[INFO] |        +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |        \- com.fasterxml:aalto-xml:jar:1.0.0:compile
[INFO] +- com.azure.resourcemanager:azure-resourcemanager-trafficmanager:jar:2.1
.0:compile
[INFO] \- junit:junit:jar:3.8.1:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.879 s
[INFO] Finished at: 2021-02-07T23:43:39-08:00
[INFO] ------------------------------------------------------------------------

```
Regards
Thilaga

**Comment by SrinivasGanesan** [comment]
Hi @thilagak ,

After tried many examples, following one is working for me. ( code and set of dependency )

Add all these dependency in pom.xml file.

`<properties>
		<java.version>1.8</java.version>
		<azure.version>3.1.0</azure.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20180813</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-core-http-netty</artifactId>
			<version>1.7.1</version>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-bom</artifactId>
			<version>4.1.52.Final</version>
			<type>pom</type>
		</dependency>

		<dependency>
			<groupId>io.projectreactor.netty</groupId>
			<artifactId>reactor-netty</artifactId>
		</dependency>

		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-handler</artifactId>
		</dependency>

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
		</dependency>


		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-file-datalake</artifactId>
			<version>12.4.0</version>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.2.2</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>msal4j</artifactId>
			<version>1.7.1</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
			<groupId>com.googlecode.json-simple</groupId>
			<artifactId>json-simple</artifactId>
			<version>1.1.1</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
		</dependency>`

Working example: ( using account name and account Key )

`try {
			StorageSharedKeyCredential credential = new StorageSharedKeyCredential(accountName, accountKey);

			String endpoint = "https://" + accountName + ".dfs.core.windows.net";

			DataLakeServiceClient storageClient = new DataLakeServiceClientBuilder().endpoint(endpoint)
					.credential(credential).buildClient();

			DataLakeFileSystemClient dataLakeFileSystemClient = storageClient.getFileSystemClient(fileSystem);

                        // Sub - Directory
			DataLakeDirectoryClient directoryClient = dataLakeFileSystemClient.getDirectoryClient(filePath);

			//DataLakeFileClient fileClient = dataLakeFileSystemClient.createFile("HelloWorld.txt");
			
			DataLakeFileClient fileClient = directoryClient.getFileClient("HelloWorld.txt");

			String data = "Sample text Contents to the file...!";
			
			InputStream dataStream = new ByteArrayInputStream(data.getBytes(StandardCharsets.UTF_8));
			
			fileClient.create();
			
			fileClient.append(dataStream, 0 , data.length());
			
			PathInfo path = fileClient.flush(data.length());
			
			System.out.println(path.toString());

		} catch (Exception e) {
			System.out.println("Error Msg" + e.getMessage());
		}`

**Comment by SrinivasGanesan** [comment]
For More info, refer [(https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/BasicExample.java#L93)]

**Comment by alzimmermsft** [comment]
@thilagak, BOM handling is one spot I wish the Maven diagnostic tooling had more clarity. 

The POM configuration you are using has [spring-boot-starter-parent](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-parent/2.0.3.RELEASE) as the parent POM and it has the [Netty BOM](https://mvnrepository.com/artifact/io.netty/netty-bom/4.1.25.Final) as a managed (BOM/dependencyManagement) dependency. Your POM doesn't explicitly include Netty POMs or the Netty BOM as an explicitly versioned dependency, so Maven will attempt to resolve this using its parent's configuration which will resolve to the older Netty BOM. Unfortunately, `dependency:tree` doesn't indicate that this was resolved using a BOM and worse it makes it appear as though `azure-core-http-netty` resolved the dependency even though [here](https://mvnrepository.com/artifact/com.azure/azure-core-http-netty/1.6.3) you can see it using a much later version.

**Comment by malmyros** [comment]
This is still an issue, can you fix the dependency so we can use it?

**Comment by kindlychung** [comment]
Following this guide and still got the same issue: https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started

Please reopen.

**Comment by AlejandroBlanco** [comment]
I verify HttpClientConfig is not found at runtime by cosmos client despite having no issue in building. Netty dependency is still an issue in azure-cosmos 1.16 and 1.17. Excluding its internal netty dependencies and/or adding them apart won't solve the issue.

**Comment by alzimmermsft** [comment]
Apologies for not seeing the responses after this issue has been closed.

@malmyros, @kindlychung, @AlejandroBlanco, @BSCrumpton, would it be possible to file issues for the errors you're running into so they can be handled separately from this issue? For each the major pieces of information needed are other dependencies being used alongside the SDKs and any special runtime environments such as DataBricks, Functions, Spark, etc being used (basically any runtime that may pollute the classpath).

**Comment by mr-konstantin-ivanov** [comment]
@thilagak if you look at your exception:

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientSecure
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:217)
```

you will notice that `reactor.netty.http.client.HttpClientSecure` and `reactor.netty.http.client.HttpClientConnect` are actually within the same package. There could be many reasons for `java.lang.NoClassDefFoundError` to be thrown (not only missing dependencies, but also failed to initialize class), so in a sense it is quite ambiguous.

I had the same problem and for me the problem turned out to be in a failure to initialize the static fields within `reactor.netty.http.client.HttpClientSecure` class itself.

Adding the latest version of netty boringssl fixed the problem:
```
                <dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
		</dependency>
```

here is a working example of my pom.xml:

```
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-storage-blob</artifactId>
			<version>12.14.0</version>
		    <exclusions>
				<exclusion>
					<groupId>com.azure</groupId>
					<artifactId>azure-core-http-netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.azure.resourcemanager</groupId>
			<artifactId>azure-resourcemanager</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.3.6</version>
		    <exclusions>
				<exclusion>
					<groupId>com.azure</groupId>
					<artifactId>azure-core-http-netty</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.11.0</version>
        </dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
		    <version>3.4.10</version><!--$NO-MVN-MAN-VER$ -->
		</dependency>
	 	<dependency>
			<groupId>io.projectreactor.netty</groupId>
			<artifactId>reactor-netty</artifactId>
	 		<version>1.0.11</version><!--$NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative-boringssl-static</artifactId>
			<version>2.0.43.Final</version><!--$NO-MVN-MAN-VER$ -->
		</dependency>
```

**Comment by LeHaine** [comment]
**Disclaimer:** This won't  help if you want to be using `reactor-netty`.

I was running into a similar issue of with the `HttpClientConfig` not able to initialize due to ` Caused by: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientConfig at reactor.netty.http.client.HttpClientConnect.<init>(HttpClientConnect.java:83)` exception in an azure queue function once deployed. Everything ran fine locally. I tried all the possibilities above, including the `azure-sdk-bom` and nothing helped.

What I ended up doing was completely excluding `azure-core-http-netty` on all of the `com.azure` dependencies and then added the `azure-core-http-okhttp` artifact. Doing that made everything work as it should.

Example of **pom.xml**:

```XML
   <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-sdk-bom</artifactId>
                <version>1.0.6</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure.functions</groupId>
            <artifactId>azure-functions-java-library</artifactId>
            <version>${azure.functions.java.library.version}</version>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-http-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-file-share</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-http-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-storage-queue</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-http-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-okhttp</artifactId>
        </dependency>
</dependencies>
```

**Comment by liukaiAs** [comment]
I also have this problem. Who has solved it？help pls
