### ISSUE TITLE
How to authorize using management libraries and Custom Script Extension

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21779]
From our gitter: https://gitter.im/Azure/azure-sdk-for-java

> I’ve created VMSS by ARM where added Custom Script Extension with protectedSetting. The protectedSettings are stored on Azure Key Vault. When i try to obtain protectedSetting for scale set by calling azure.virtualMachineScaleSets().getByResourceGroup(rename, scaleSetName) getting null for custom script extension protectedSetting. Could you help me with what could be an issue? Thanks in advance!

/cc @yungezz

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help look at this

**Comment by weidongxu-microsoft** [comment]
I assume the behavior is intended. `protectedSetting` is secret. If you need it, get it again from key vault.

**Comment by ivan-83** [comment]
@weidongxu-microsoft Thanks for responding.  I’ve deployed VMSS from the ARM template where I stated storage account name and key as Key Vault references within the custom extension script protectedSettings section.  Are Vault references also considered secrets? Does it mean whatever I put within ARM custom extension protectedSettings section while deploying VMSS, the value of protectedSettings will be null in [getting VMSS REST API ](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/get)response and as result of SDK azure.virtualMachineScaleSets().getByResourceGroup(rename, scaleSetName) call? Should I assign any additional role to my enterprise application on Azure which using as the service provider for getting the scale sets?

**Comment by weidongxu-microsoft** [comment]
@ivan-83 
I am not sure about the ARM template specifying Key Vault reference. But if your setting is `storageAccountName` and `storageAccountKey`, at least the `storageAccountKey` is a secret.
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-linux#property-value-details

Assume above is correct, I still do not get why you need to get the key. If you've saved it in key vault, why just read key vault for it?

**Comment by ivan-83** [comment]
@weidongxu-microsoft 
The use case is, storageAccountName and storageAccountKey protected settings are set by a third party, we just need to obtain the settings values on our side by consuming REST API or Java SDK lib.

**Comment by weidongxu-microsoft** [comment]
@Drewm3 @amjads1 Is there solution for user to retrieve protected setting in vmss extension?

**Comment by weidongxu-microsoft** [comment]
@ivan-83 

I still do not think secret should be transferred this way. Anyway I've involved service team for better suggestion.

**Comment by ivan-83** [comment]
Thanks @weidongxu-microsoft

**Comment by amjads1** [comment]
Thanks for the add @weidongxu-microsoft !

@ivan-83  - This is the expected behavior as protectedSetting is for secret. We don't return any protectedSettings on GETs today as they will contain secrets. Closing this issue for now but let me know if you have any further questions.

**Comment by weidongxu-microsoft** [comment]
@ivan-83

Compute service confirmed that `protectedSetting` cannot be read.

Let me know if there is other question.
