### ISSUE TITLE
Connection timeout followed by Authentication issue.

### ISSUE THREAD

**Issue by VIJAY-SUBRAMANIAM** [Azure/azure-sdk-for-java#9124]
Azure upload process throws connection timeout followed by an Authentication issue. This happens every time after an idle period.  I use azure v12.5.0 and it uses netty 4.1.44.Final

It seems whenever max idle timeout is reached, the authentication header becomes old.

I use default Azure bob client configuration. Please guide me if there is any settings required to solve this problem. 

Here are the logs

2020-03-15 00:00:25,570 [a8c597cc8a78] [20200314235159971-2] INFO  com.sonymusic.delivery.azure.transfer.MultipleFileUpload - Uploading File{sourceFile='R38/BatchManifest/20200314235159971/BatchComplete_20200314235159971.xml', sourceFileSize=2251, sourceFileHash='cca70yI179oguzn4VEjgJw==', targetFile='/tmp/R38/manifest/BatchComplete_20200314235159971.xml'}
 
2020-03-15 00:00:25,570 [a8c597cc8a78] [20200314235159971-2] INFO  com.sonymusic.delivery.aws.s3.S3SingletonClient - getting input stream of object s3://R38/BatchManifest/20200314235159971/BatchComplete_20200314235159971.xml
2020-03-15 00:00:25,623 [a8c597cc8a78] [20200314235159971-2] INFO  com.sonymusic.delivery.azure.client.AzureStorageClient - Uploading a stream to https://******.blob.core.windows.net/dropoff tmp/R38/manifest/BatchComplete_20200314235159971.xml

..
..

2020-03-15 00:17:05,195 [a8c597cc8a78] [reactor-http-epoll-19] WARN  reactor.netty.http.client.HttpClientConnect - [id: 0xf36cb006, L:/172.17.0.5:56846 - R:****.blob.core.windows.net/*****:443] The connection observed an error
io.netty.channel.unix.Errors$NativeIoException: read(..) failed: Connection timed out
2020-03-15 00:17:09,682 [a8c597cc8a78] [20200314235159971-2] ERROR com.sonymusic.delivery.azure.transfer.UploadTransferManager - Error delivering contents related to id=20200314235159971. Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c083ce6d-801e-007b-0e5f-fab8af000000
Time:2020-03-15T00:17:09.5735853Z</Message><AuthenticationErrorDetail>Request date header too old: 'Sun, 15 Mar 2020 00:00:25 GMT'</AuthenticationErrorDetail></Error>"
com.azure.storage.blob.models.BlobStorageException: Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:c083ce6d-801e-007b-0e5f-fab8af000000
Time:2020-03-15T00:17:09.5735853Z</Message><AuthenticationErrorDetail>Request date header too old: 'Sun, 15 Mar 2020 00:00:25 GMT'</AuthenticationErrorDetail></Error>"
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.azure.core.http.rest.RestProxy.instantiateUnexpectedException(RestProxy.java:357) ~[azure-core-1.3.0.jar:?]
	at com.azure.core.http.rest.RestProxy.lambda$ensureExpectedStatus$3(RestProxy.java:400) ~[azure-core-1.3.0.jar:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:320) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:337) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2199) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onSubscribe(MonoCacheTime.java:276) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:191) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:132) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:48) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:112) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:213) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:123) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:178) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxContextStart$ContextStartSubscriber.onNext(FluxContextStart.java:103) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1637) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136) ~[reactor-core-3.3.2.RELEASE.jar:?]
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:419) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:209) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:367) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:572) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:90) ~[reactor-netty-0.9.4.RELEASE.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[netty-transport-4.1.44.Final.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.44.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316) ~[netty-codec-4.1.44.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.44.Final.jar:?]
		

https://github.com/reactor/reactor-netty/issues/962
https://github.com/reactor/reactor-netty/issues/564

**Comment by joshfree** [comment]
Thanks for reporting this issue @VIJAY-SUBRAMANIAM.  @alzimmermsft @rickle-msft can you please take a look?

**Comment by rickle-msft** [comment]
Hi, @VIJAY-SUBRAMANIAM. Thank you for opening this issue. The Authentication header does have a lifespan of around 15 minutes, and we don't sign each retry, so if you have a large number of retries enabled or a long backoff period between retries, you're likely to hit this scenario. For the purposes of experimentation, could you please configure a smaller number of timeouts and shorter backoff interval to see if that solves the problem? And then we can go from there if those values aren't acceptable in your environment.

**Comment by VIJAY-SUBRAMANIAM** [comment]
Hi, @rachel-msft,

I'm using default retry values provided by API class RequestRetryOptions.  I see the default of 4 retries with shorter backoff interval min 4ms and max 120ms.   only default timeout set to max integer 2147483647.  I'm afraid a smaller timeout will probably not be sufficient for large size file transfer.  our case transfer file size vary between 10 KB to 1TB.    can configure timeout based on the file size (60 seconds per MB as per documentation) for each client creation. Will that work? or still, want to try with a smaller value like 300 seconds for this experimentation?

**Comment by VIJAY-SUBRAMANIAM** [comment]
Hi @rachel-msft ,

I'm trying to find how to socket/read timeout on the netty channel.  let me know if Azure API provides a way to configure those values?

**Comment by rachel-msft** [comment]
@rickle-msft

**Comment by rickle-msft** [comment]
@VIJAY-SUBRAMANIAM Thank you for that information. What api are you calling to upload your files? I don't think Azure Core gives you access to the netty channels directly, but it might be an option on the Netty http client that you can pass to your builder.

**Comment by VIJAY-SUBRAMANIAM** [comment]
Hi @rickle-msft 

Here are the API details and my azure client code

compile group: 'com.azure', name: 'azure-storage-blob', version: '12.5.0'
compile group: 'com.azure', name: 'azure-storage-common', version: '12.5.0'


`package com.sonymusic.delivery.azure.client;

import com.azure.storage.blob.*;
import com.azure.storage.blob.models.AccessTier;
import com.azure.storage.blob.models.BlobHttpHeaders;
import com.azure.storage.blob.models.ListBlobsOptions;
import com.azure.storage.blob.models.ParallelTransferOptions;
import com.azure.storage.blob.specialized.BlockBlobAsyncClient;
import com.azure.storage.common.StorageSharedKeyCredential;
import com.sonymusic.delivery.util.PropertyReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URLConnection;
import java.nio.file.Files;
import java.time.Duration;
import java.util.List;
import java.util.stream.Collectors;

public class AzureStorageClient {
    public static final int KB = 1024;
    private static final int MB = KB * 1024;
    private static final Logger LOGGER = LoggerFactory.getLogger(AzureStorageClient.class);
    private static final PropertyReader PROPERTY_READER;

    private final StorageSharedKeyCredential credential;

    static {
        PROPERTY_READER = PropertyReader.INSTANCE;
    }

    public static AzureStorageClient.AzureStorageClientBuilder builder() {
        return new AzureStorageClient.AzureStorageClientBuilder();
    }

    public static AzureStorageClient create() {
        return builder()
                .accountName(PROPERTY_READER.getBlobAccountName())
                .accountKey(PROPERTY_READER.getBlobAccountKey())
                .build();
    }

    private AzureStorageClient(final String accountName, final String accountKey) {
        this.credential = new StorageSharedKeyCredential(accountName, accountKey);
    }

    /**
     * list blobs and returns list of blob name
     *
     * @param endPoint           - azure storage endpoint
     * @param acknowledgementDir -  A prefix that a blob must match to be returned
     */
    public List<String> listBlobs(final String endPoint, final String acknowledgementDir) {
        String newEndPoint = removeLastFwdSlashCharacter(endPoint);
        String newAckDir = removeFirstFwdSlashCharacter(acknowledgementDir);
        LOGGER.info("Downloading acknowledgement files from {} {}", newEndPoint, newAckDir);
        //Create a BlobContainerClient
        BlobContainerClient client = getBlobContainerClient(newEndPoint);

        ListBlobsOptions options = new ListBlobsOptions();
        options.setMaxResultsPerPage(100); //TODO max settings not working with prefix, default is 5000
        if (newAckDir != null) {
            options.setPrefix(newAckDir); //directory name
        }
        final List<String> blobNameList = client.listBlobs(options, Duration.ofMinutes(2)).stream()
                .filter(blobItem -> !blobItem.isDeleted()).map(blobItem -> blobItem.getName()).collect(Collectors.toList());
        LOGGER.info("The following files {} in the location {} {}", blobNameList, newEndPoint, newAckDir);
        return blobNameList;
    }

    //upload a file to blob storage
    public void upload(final File localFile, final String endPoint, final String blobName) throws IOException {
        String newEndPoint = removeLastFwdSlashCharacter(endPoint);
        String newBlobName = removeFirstFwdSlashCharacter(blobName);
        LOGGER.info("Uploading {} to {} {}", localFile, newEndPoint, newBlobName);
        // Create a BlobClient
        BlobClient blobClient = getBlobClient(newEndPoint, newBlobName);

        long startTime = System.currentTimeMillis();
        //upload file
        blobClient.uploadFromFile(localFile.getPath(), getParallelTransferOptions(blobName, localFile.length()), getBlobHttpHeaders(localFile), null,
                AccessTier.fromString(PROPERTY_READER.getBlobTier(AccessTier.HOT.toString())), null, null);
        LOGGER.info("The file {} upload succeeded", blobName);
        printThroughput(blobName, localFile.length(), startTime);
    }

    //upload a stream to blob storage
    public void upload(final InputStream inputStream, final String endPoint, final String blobName, final long length) throws IOException {
        String newEndPoint = removeLastFwdSlashCharacter(endPoint);
        String newBlobName = removeFirstFwdSlashCharacter(blobName);
        LOGGER.info("Uploading a stream to {} {}", newEndPoint, newBlobName);
        // Create a BlobClient
        BlobClient blobClient = getBlobClient(newEndPoint, newBlobName);

        long startTime = System.currentTimeMillis();
        //upload a stream to blob storage
        blobClient.uploadWithResponse(inputStream, length, getParallelTransferOptions(blobName, length),
                getBlobHttpHeaders(inputStream), null, AccessTier.fromString(PROPERTY_READER.getBlobTier(AccessTier.HOT.toString())), null,
                null, null);

        LOGGER.info("The stream {} upload succeeded", blobName);
        printThroughput(blobName, length, startTime);
    }

    private void printThroughput(final String blobName, final long fileSize, final long startTime) {
        double time = (System.currentTimeMillis() - startTime) / 1000d;
        double size = (double) fileSize / MB;
        double throughput = size / time;
        LOGGER.info(String.format("The file %s transferred with rate of %.2f MB/s.", blobName, throughput));
    }

    //Create a parallel transfer options
    //TODO progress shows for only one file upload even if its concurrent upload
    private ParallelTransferOptions getParallelTransferOptions(final String blobName, final long fileSize) {
        return new ParallelTransferOptions(
                PROPERTY_READER.getBlobBlockSize(BlobAsyncClient.BLOB_DEFAULT_UPLOAD_BLOCK_SIZE),
                PROPERTY_READER.getBlobNumBuffers(),
                byteTransferred -> {
                    if (byteTransferred % BlockBlobAsyncClient.MAX_UPLOAD_BLOB_BYTES == 0) {
                        int percent = (int) ((byteTransferred * 100) / fileSize);
                        LOGGER.info("{} : {}% percent of transfer completed", blobName, percent);
                    }
                },
                PROPERTY_READER.getMaxSingleBlobUploadSize(BlockBlobAsyncClient.MAX_STAGE_BLOCK_BYTES));
    }

    //Create a BlobHttpHeader  accepts file as input
    private BlobHttpHeaders getBlobHttpHeaders(final File localFile) throws IOException {
        return new BlobHttpHeaders()
                .setContentType(Files.probeContentType(localFile.toPath()));
    }

    //Create a BlobHttpHeader accepts input stream as input
    private BlobHttpHeaders getBlobHttpHeaders(final InputStream stream) throws IOException {
        return new BlobHttpHeaders()
                .setContentType(URLConnection.guessContentTypeFromStream(stream));
    }

    //Create a BlobClient
    private BlobClient getBlobClient(final String endPoint, final String blobName) {
        return new BlobClientBuilder()
                .credential(credential)
                .endpoint(endPoint)
                .blobName(blobName)
                .buildClient();
    }

    //create a BlobContainerClient
    private BlobContainerClient getBlobContainerClient(final String endPoint) {
        // Create a containerClient
        return new BlobContainerClientBuilder()
                .credential(credential)
                .endpoint(endPoint)
                .buildClient();
    }

    private String removeLastFwdSlashCharacter(final String value) {
        if (value != null) {
            var idx = value.lastIndexOf('/');
            if (idx == (value.length() - 1)) {
                return value.substring(0, idx);
            }
        }
        return value;
    }

    private String removeFirstFwdSlashCharacter(final String value) {
        if (value != null) {
            var idx = value.indexOf('/');
            if (idx == 0) {
                return value.substring(1);
            }
        }
        return value;
    }

    public static class AzureStorageClientBuilder {
        private String accountName;
        private String accountKey;

        AzureStorageClientBuilder() {
        }

        public AzureStorageClient.AzureStorageClientBuilder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        public AzureStorageClient.AzureStorageClientBuilder accountKey(String accountKey) {
            this.accountKey = accountKey;
            return this;
        }

        public AzureStorageClient build() {
            return new AzureStorageClient(this.accountName, this.accountKey);
        }

        public String toString() {
            return "AzureStorageClient.AzureStorageClientBuilder(accountName=" + this.accountName + ", accountKey=" + this.accountKey + ")";
        }
    }
}`

**Comment by rickle-msft** [comment]
@VIJAY-SUBRAMANIAM Thank you for sharing this code. And can you please share what you mean by "idle period" and "idle timeout" in your original post? It doesn't look like you're setting timeouts on the upload operations, so I'm not sure what timeout you're hitting, and I'm not sure what could be making the program sit idly

**Comment by VIJAY-SUBRAMANIAM** [comment]
Hi @rickle-msft 

Idle Period when no upload activity is being performed by application/process.  our process receives messages at the interval and pushes content to Azure Storage. The application is dockerized

This issue reproducible every time a lot of concurrent upload activity following by an idle period of no activity performed by the process, and then, the first upload activity after an idle period causes timeout and authentication issue.  This is happening on Azure/Netty side.

It seems netty max idle timeout is reached, connection closed and recreation takes time..can smaller netty timeout & retry handled in Azure core?

**Comment by rickle-msft** [comment]
@VIJAY-SUBRAMANIAM 

My apologies for the delay. @alzimmermsft is doing some work to investigate better handling of timeouts/delays on uploads and potentially putting that into core. We are hoping those changes can make it into the release in early May. I think our best course of action is to allow that work to be released and see if that mitigates this issue at all as I believe it should. Also note that there was recently a fix merged to recalculate the authorization header after issuing a retry to prevent it from going stale, so that should help as well.

**Comment by VIJAY-SUBRAMANIAM** [comment]
@rickle-msft,  Thanks for update.  May I know when recalculation changes available in Maven central repo?

**Comment by Petermarcu** [comment]
@alzimmermsft @rickle-msft whats the latest update on this. Did we roll out changes and can this issue be resolved?

**Comment by alzimmermsft** [comment]
@VIJAY-SUBRAMANIAM, @Petermarcu, there was an issue where a new `Date` header wasn't applied on request retry, this should be resolved in `azure-storage-blob` versions `12.6.0` and above. If needed I can get the other Storage library versions that took this fix.

On-going work is still occurring around better idle timeout logic. @VIJAY-SUBRAMANIAM this [API](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java#L62) in the `NettyAsyncHttpClientBuilder` should allow you to pass a pre-configured Netty `HttpClient` instance that our wrapper will use as the base `HttpClient` during construction. This should allow you to configure more targeted Netty handling.

**Comment by gapra-msft** [comment]
This issue was resolved with this PR in v12.6.0+.

https://github.com/Azure/azure-sdk-for-java/pull/9529

Closing this issue as a result. If you have any more issues, feel free to open a new issue, and we'd be happy to help!
